### PR TITLE
Fix Deprecation Errors for Atom API 1.0

### PR DESCRIPTION
**Pull request by framerate**

### CODE REVIEW

**Comment by framerate** [comment]
pinging @jamischarles 

My heavy atom workflow has now gotten all errors fixed except for your package!

**Comment by jamischarles** [comment]
Will try to take a look at this soon. Anybody interested in sharing ownership of this package?

**Comment by framerate** [comment]
I don't mind assisting with it, I'd just like someone to take a look here: https://github.com/jamischarles/atom-todo-show/issues/34 and let me know about the stuff I removed and if it's still necessary.

**Comment by jamischarles** [comment]
Looks great. Seems to work as expected. Thanks!

**Comment by framerate** [comment]
Thank you @jamischarles! This plugin helps me a lot!

**Pull request merged**
